### ISSUE TITLE
netty 网关该怎么实现

### ISSUE THREAD

**Issue by aaaaaaanthony** [xuminwlt/j360-netty-parent#1]
网关用来转发长链接

**Comment by xuminwlt** [comment]
@YangAnLin 在Server端创建Client端Bootstrap连接，代理转发

**Comment by aaaaaaanthony** [comment]
参考netty官网的example  ,  网关创建了bootStrap   和目标服务器创建了链接, 发送完消息之后,网关就和目标服务器断开了链接,这是正常的吗?我不想断开

**Comment by xuminwlt** [comment]
demo是断开的，将Bootstrap的agent client链接池化不断开，如果不加入idle空闲检测，则一直保持连接

**Comment by aaaaaaanthony** [comment]
好的,谢谢

**Comment by xuminwlt** [comment]
@YangAnLin 我这个agent工程是空的 我写一份代理吧
